language: en-US
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_instructions:
    - path: "src/**"
      instructions: |
        Review for XSS vulnerabilities — never use innerHTML, always textContent.
        Check for immutability violations — never mutate input objects.
        Verify regex patterns are not susceptible to ReDoS.
    - path: "tests/**"
      instructions: |
        Verify tests cover edge cases and error paths.
        Check test isolation — no shared mutable state.
    - path: ".github/workflows/**"
      instructions: |
        Check for command injection via untrusted GitHub context variables.
        Verify secrets are not exposed in logs.
chat:
  auto_reply: true
