import { describe, it, expect } from 'vitest'
import { extractYaml } from '../src/extract'

describe('extractYaml', () => {
  it('returns pure YAML as-is', () => {
    const yaml = 'services:\n  app:\n    image: nginx\n'
    const result = extractYaml(yaml)
    expect(result.yaml).toBe(yaml.trim())
    expect(result.error).toBeNull()
  })

  it('strips leading shell command', () => {
    const input = '$ sudo docker compose config\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.yaml).not.toContain('$ sudo')
    expect(result.error).toBeNull()
  })

  it('strips leading blank lines', () => {
    const input = '\n\n\n  \nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })

  it('strips trailing terminal prompt', () => {
    const input = 'services:\n  app:\n    image: nginx\nuser@host:~$ '
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.yaml).not.toContain('user@host')
    expect(result.error).toBeNull()
  })

  it('returns error for pure garbage text', () => {
    const result = extractYaml('this is just some random text with no yaml')
    expect(result.error).toBeTruthy()
    expect(result.yaml).toBeNull()
  })

  it('returns error for empty input', () => {
    const result = extractYaml('')
    expect(result.error).toBeTruthy()
    expect(result.yaml).toBeNull()
  })

  it('returns error for whitespace-only input', () => {
    const result = extractYaml('   \n  \n  ')
    expect(result.error).toBeTruthy()
    expect(result.yaml).toBeNull()
  })

  it('handles docker run command before YAML', () => {
    const input = '$ docker run --rm ghcr.io/red5d/docker-autocompose sonarr\nservices:\n  sonarr:\n    image: linuxserver/sonarr\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.yaml).not.toContain('docker run')
    expect(result.error).toBeNull()
  })

  it('handles comment lines before YAML', () => {
    const input = '# Generated by docker-autocompose\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })

  it('suggests copy issue for truncated YAML', () => {
    const input = 'services:\n  app:\n    image: nginx\n    environment:\n      - FOO='
    const result = extractYaml(input)
    // Should still try to parse — truncated YAML may or may not be valid
    // The key is we don't crash
    expect(result.error === null || typeof result.error === 'string').toBe(true)
  })

  it('handles version key at start', () => {
    const input = 'version: "3.6"\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })

  it('handles name key at start (docker compose config style)', () => {
    const input = 'name: myproject\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })
})
