import { describe, it, expect } from 'vitest'
import { stripNoise } from '../src/noise'

describe('stripNoise', () => {
  it('removes com.docker.compose.* labels from services', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          labels: {
            'com.docker.compose.project': 'myapp',
            'com.docker.compose.service': 'app',
            'traefik.enable': 'true',
          },
        },
      },
    }
    const result = stripNoise(input)
    const labels = (result['services'] as Record<string, Record<string, unknown>>)['app']?.['labels'] as Record<string, unknown>
    expect(labels).not.toHaveProperty('com.docker.compose.project')
    expect(labels).not.toHaveProperty('com.docker.compose.service')
    expect(labels).toHaveProperty('traefik.enable', 'true')
  })

  it('removes default network with no custom config', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      networks: {
        default: {
          external: false,
        },
      },
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('networks')
  })

  it('keeps networks with custom config', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      networks: {
        proxy: {
          external: true,
        },
      },
    }
    const result = stripNoise(input)
    expect(result).toHaveProperty('networks')
  })

  it('removes top-level empty volumes', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      volumes: {},
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('volumes')
  })

  it('keeps top-level volumes with entries', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      volumes: { data: { driver: 'local' } },
    }
    const result = stripNoise(input)
    expect(result).toHaveProperty('volumes')
  })

  it('removes version key', () => {
    const input = {
      version: '3.6',
      services: { app: { image: 'nginx' } },
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('version')
  })

  it('removes null/empty fields recursively', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          entrypoint: null,
          command: '',
          labels: {},
        },
      },
    }
    const result = stripNoise(input)
    const app = (result['services'] as Record<string, Record<string, unknown>>)['app']
    expect(app).not.toHaveProperty('entrypoint')
    expect(app).not.toHaveProperty('command')
    expect(app).not.toHaveProperty('labels')
    expect(app).toHaveProperty('image', 'nginx')
  })

  it('does not mutate the input', () => {
    const input = {
      version: '3.6',
      services: {
        app: {
          image: 'nginx',
          labels: {
            'com.docker.compose.project': 'myapp',
          },
        },
      },
    }
    const inputCopy = JSON.parse(JSON.stringify(input))
    stripNoise(input)
    expect(input).toEqual(inputCopy)
  })

  it('handles services with only noise fields gracefully', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          labels: {
            'com.docker.compose.project': 'myapp',
          },
          entrypoint: null,
        },
      },
    }
    const result = stripNoise(input)
    const app = (result['services'] as Record<string, Record<string, unknown>>)['app']
    expect(app).toHaveProperty('image', 'nginx')
    expect(app).not.toHaveProperty('labels')
    expect(app).not.toHaveProperty('entrypoint')
  })

  it('handles array-style labels (removes compose labels)', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          labels: [
            'com.docker.compose.project=myapp',
            'com.docker.compose.service=app',
            'traefik.enable=true',
          ],
        },
      },
    }
    const result = stripNoise(input)
    const labels = (result['services'] as Record<string, Record<string, unknown>>)['app']?.['labels'] as string[]
    expect(labels).toEqual(['traefik.enable=true'])
  })

  it('removes name key (auto-generated by docker compose config)', () => {
    const input = {
      name: 'myproject',
      services: { app: { image: 'nginx' } },
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('name')
  })
})
