import { describe, it, expect } from 'vitest'
import { stripNoise } from '../src/noise'

describe('stripNoise', () => {
  it('removes com.docker.compose.* labels from services', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          labels: {
            'com.docker.compose.project': 'myapp',
            'com.docker.compose.service': 'app',
            'traefik.enable': 'true',
          },
        },
      },
    }
    const result = stripNoise(input)
    const labels = (result['services'] as Record<string, Record<string, unknown>>)['app']?.['labels'] as Record<string, unknown>
    expect(labels).not.toHaveProperty('com.docker.compose.project')
    expect(labels).not.toHaveProperty('com.docker.compose.service')
    expect(labels).toHaveProperty('traefik.enable', 'true')
  })

  it('removes default network with no custom config', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      networks: {
        default: {
          external: false,
        },
      },
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('networks')
  })

  it('keeps networks with custom config', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      networks: {
        proxy: {
          external: true,
        },
      },
    }
    const result = stripNoise(input)
    expect(result).toHaveProperty('networks')
  })

  it('removes top-level empty volumes', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      volumes: {},
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('volumes')
  })

  it('keeps top-level volumes with entries', () => {
    const input = {
      services: { app: { image: 'nginx' } },
      volumes: { data: { driver: 'local' } },
    }
    const result = stripNoise(input)
    expect(result).toHaveProperty('volumes')
  })

  it('removes version key', () => {
    const input = {
      version: '3.6',
      services: { app: { image: 'nginx' } },
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('version')
  })

  it('removes null/empty fields recursively', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          entrypoint: null,
          command: '',
          labels: {},
        },
      },
    }
    const result = stripNoise(input)
    const app = (result['services'] as Record<string, Record<string, unknown>>)['app']
    expect(app).not.toHaveProperty('entrypoint')
    expect(app).not.toHaveProperty('command')
    expect(app).not.toHaveProperty('labels')
    expect(app).toHaveProperty('image', 'nginx')
  })

  it('does not mutate the input', () => {
    const input = {
      version: '3.6',
      services: {
        app: {
          image: 'nginx',
          labels: {
            'com.docker.compose.project': 'myapp',
          },
        },
      },
    }
    const inputCopy = JSON.parse(JSON.stringify(input))
    stripNoise(input)
    expect(input).toEqual(inputCopy)
  })

  it('handles services with only noise fields gracefully', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          labels: {
            'com.docker.compose.project': 'myapp',
          },
          entrypoint: null,
        },
      },
    }
    const result = stripNoise(input)
    const app = (result['services'] as Record<string, Record<string, unknown>>)['app']
    expect(app).toHaveProperty('image', 'nginx')
    expect(app).not.toHaveProperty('labels')
    expect(app).not.toHaveProperty('entrypoint')
  })

  it('handles array-style labels (removes compose labels)', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          labels: [
            'com.docker.compose.project=myapp',
            'com.docker.compose.service=app',
            'traefik.enable=true',
          ],
        },
      },
    }
    const result = stripNoise(input)
    const labels = (result['services'] as Record<string, Record<string, unknown>>)['app']?.['labels'] as string[]
    expect(labels).toEqual(['traefik.enable=true'])
  })

  it('removes name key (auto-generated by docker compose config)', () => {
    const input = {
      name: 'myproject',
      services: { app: { image: 'nginx' } },
    }
    const result = stripNoise(input)
    expect(result).not.toHaveProperty('name')
  })

  it('removes default Docker fields from autocompose output', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          ipc: 'private',
          working_dir: '/',
          entrypoint: ['/init'],
          hostname: 'myhost',
        },
      },
    }
    const result = stripNoise(input)
    const app = (result['services'] as Record<string, Record<string, unknown>>)['app']
    expect(app).not.toHaveProperty('ipc')
    expect(app).not.toHaveProperty('working_dir')
    expect(app).not.toHaveProperty('entrypoint')
    expect(app).toHaveProperty('hostname', 'myhost')
  })

  it('keeps non-default entrypoint', () => {
    const input = {
      services: {
        app: {
          image: 'nginx',
          entrypoint: ['/custom-entrypoint.sh'],
        },
      },
    }
    const result = stripNoise(input)
    const app = (result['services'] as Record<string, Record<string, unknown>>)['app']
    expect(app).toHaveProperty('entrypoint')
  })

  it('strips container-internal env vars from image defaults (dict style)', () => {
    const input = {
      services: {
        app: {
          image: 'linuxserver/sonarr',
          environment: {
            S6_BEHAVIOUR_IF_STAGE2_FAILS: '2',
            S6_CMD_WAIT_FOR_SERVICES_MAXTIME: '0',
            IMAGE_STATS: 'base64data',
            APP_DIR: '/app',
            CONFIG_DIR: '/config',
            XDG_CONFIG_HOME: '/config/.config',
            XDG_CACHE_HOME: '/config/.cache',
            XDG_DATA_HOME: '/config/.local/share',
            PUID: '1000',
            TZ: 'America/New_York',
            API_KEY: 'secret123',
          },
        },
      },
    }
    const result = stripNoise(input)
    const env = (result['services'] as Record<string, Record<string, unknown>>)['app']?.['environment'] as Record<string, unknown>
    expect(env).not.toHaveProperty('S6_BEHAVIOUR_IF_STAGE2_FAILS')
    expect(env).not.toHaveProperty('S6_CMD_WAIT_FOR_SERVICES_MAXTIME')
    expect(env).not.toHaveProperty('IMAGE_STATS')
    expect(env).not.toHaveProperty('APP_DIR')
    expect(env).not.toHaveProperty('CONFIG_DIR')
    expect(env).not.toHaveProperty('XDG_CONFIG_HOME')
    expect(env).not.toHaveProperty('XDG_CACHE_HOME')
    expect(env).not.toHaveProperty('XDG_DATA_HOME')
    expect(env).toHaveProperty('PUID', '1000')
    expect(env).toHaveProperty('TZ', 'America/New_York')
    expect(env).toHaveProperty('API_KEY', 'secret123')
  })

  it('strips container-internal env vars from image defaults (array style)', () => {
    const input = {
      services: {
        app: {
          image: 'linuxserver/sonarr',
          environment: [
            'S6_BEHAVIOUR_IF_STAGE2_FAILS=2',
            'IMAGE_STATS=base64data',
            'APP_DIR=/app',
            'XDG_CONFIG_HOME=/config/.config',
            'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
            'PUID=1000',
            'TZ=America/New_York',
          ],
        },
      },
    }
    const result = stripNoise(input)
    const env = (result['services'] as Record<string, Record<string, unknown>>)['app']?.['environment'] as string[]
    expect(env).not.toContain(expect.stringContaining('S6_BEHAVIOUR_IF_STAGE2_FAILS'))
    expect(env).not.toContain(expect.stringContaining('IMAGE_STATS'))
    expect(env).not.toContain(expect.stringContaining('APP_DIR'))
    expect(env).not.toContain(expect.stringContaining('XDG_CONFIG_HOME'))
    expect(env).not.toContain(expect.stringContaining('PATH='))
    expect(env).toContain('PUID=1000')
    expect(env).toContain('TZ=America/New_York')
  })

  it('strips empty env values in array style', () => {
    const input = {
      services: {
        app: {
          environment: [
            'VPN_PIA_USER=',
            'VPN_LAN_NETWORK=',
            'UNBOUND_NAMESERVERS=',
            'PUID=1000',
          ],
        },
      },
    }
    const result = stripNoise(input)
    const env = (result['services'] as Record<string, Record<string, unknown>>)['app']?.['environment'] as string[]
    expect(env).not.toContain('VPN_PIA_USER=')
    expect(env).not.toContain('VPN_LAN_NETWORK=')
    expect(env).not.toContain('UNBOUND_NAMESERVERS=')
    expect(env).toContain('PUID=1000')
  })
})
