name: Bug Report
description: Report a bug in the compose sanitizer
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **This tracker is for bugs only.** Not for general Docker/compose support.
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Redaction (sensitive value not caught or safe value wrongly redacted)
        - Noise stripping (field not removed or wrong field removed)
        - Advisory (false positive or missed detection)
        - Input extraction (YAML not parsed from pasted output)
        - UI / display issue
        - Build / deployment
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true
  - type: dropdown
    id: input-type
    attributes:
      label: Input type
      options:
        - docker-autocompose output
        - docker compose config output
        - Raw docker-compose.yml
        - Other
    validations:
      required: true
  - type: textarea
    id: input
    attributes:
      label: Input YAML (sanitized)
      description: Paste a minimal example that reproduces the issue. Redact any real secrets first.
      render: yaml
  - type: textarea
    id: output
    attributes:
      label: Actual output
      description: What the sanitizer produced
      render: yaml
  - type: input
    id: browser
    attributes:
      label: Browser
      description: e.g., Chrome 120, Firefox 121, Safari 17
