name: Feature Request
description: Suggest an improvement to the compose sanitizer
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **This tracker is for feature requests only.** Not for general Docker/compose support.
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New redaction pattern (detect additional sensitive values)
        - New noise filter (strip additional generated fields)
        - New advisory (detect additional misconfigurations)
        - Input format support (new input types)
        - Output / sharing (clipboard, export options)
        - UI / UX improvement
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why is this needed? Include example YAML if relevant.
    validations:
      required: true
